Feature/#99 팀 랭킹 구현
BDD-CLUB/01-doo-re-back pull request #100
Opened 2024-03-14 09:16 UTC by lcqff

## #️⃣ 연관된 이슈

close: #99

## 📝 작업 내용

팀 랭킹 (팀 목록조회) 를 구현했습니~ 
테스트코드 덜 짜서 아직 테스트코드는 없습니다^^; 금방 올릴게요

## 💬 리뷰 요구사항(선택)

- 쿼리문 잘 작성됐는지
- 동일 랭킹의 팀이 존재할 수 있을 거 같아 랭킹 포인트순으로 정렬한 다음 랭킹을 부여하는 식으로 로직을 짰는데 더 깔끔하게 코드를 짤 수 있을지....🤔 별로 마음에 안드네요

2024-03-28 10:45 UTC, amaran-th requested changes
한 가지 중요한 사실을 깨닫고 리뷰를 중단했는데, 확인해주시면 감사하겠습니다...!!!

2024-03-28 10:45 UTC, amaran-th commented on src/docs/asciidoc/team.adoc
> +== `GET`: 팀 랭킹(팀 록록) 조회
오타 발견👀

2024-03-28 10:45 UTC, amaran-th commented on src/main/java/doore/team/application/TeamRankPoint.java
> +}
개인적인 의견인데, 이렇게 데이터를 담기 위한 목적의 클래스를 새로 만드는 것은 객체지향적이지 않은 것 같습니다!
Map 자료구조를 활용해보는 것은 어떨까요~?

2024-03-28 10:45 UTC, amaran-th commented on src/main/java/doore/team/application/TeamQueryService.java
> +    public List<TeamRankResponse> getTeamRanks() {
⚠️⚠️⚠️
리뷰를 하다가 깨달은 건데, 저희 예전에 ERD 설계할 때, 학습자료 업로드&스터디 커리큘럼 완료를 할 때마다 텃밭 테이블에 접근해서 텃밭 값을 업데이트하고, 랭킹을 계산할 때는 텃밭 테이블 값을 불러오기로 한 것 아니었나요...?
구현이 논의된 내용과 다른 것 같습니다...!

2024-04-30 01:58 UTC, JJimini reviewed
수고하셨습니다~! 학습자료 코드랑 합쳐져있는데, 학습자료는 이미 머지된걸로 알아서 팀 랭킹 부분만 확인하였습니다!

2024-04-30 01:58 UTC, JJimini commented on src/main/java/doore/team/application/TeamQueryService.java
> +    private List<TeamRankResponse> provideRank(List<TeamRankPoint> teamRankPoints) {
랭킹을 부여하는 방식을 직접 구현하였는데, 제가 이번에 정처기를 공부하면서 `rank`에 대해 공부했던 기억이 있어 코멘트 남겨두겠습니다..! 저도 해본적은 없지만, `controller`에서 sql문을 활용해서 구현해보시는건 어떨까요??

[dense_rank_순위](https://cbwstar.tistory.com/m/entry/denserank%EC%88%9C%EC%9C%84?t_src=GNBlayer_kakaostory)

2024-05-02 06:03 UTC, lcqff commented
기존 기획 돼있던 동작과 아예 다른 거 같아서(ㅠㅠ) 텃밭과 랭킹 pr 새로 올리고 이 pr은 close 하겠습니다...

2024-05-10 08:20 UTC, closed without merging