Feature/#77 권한 관련 기능 구현
BDD-CLUB/01-doo-re-back pull request #105
Opened 2024-03-21 02:02 UTC by JJimini

## #️⃣ 연관된 이슈

close: #76 
close: #101 

## 📝 작업 내용

- 권한 관련이라고 pr 제목이 되어있지만, 실제로는 팀장 및 스터디장 위임기능과 회원탈퇴 기능 구현입니다. (그래서 close 이슈에 권한 관련은 못넣음)
    - 권한 관련을 처리하려면 로그인이 제대로 되어야하는데 여기 문제가 있어 조금 밀리는 중입니다. 시큐리티 구현에 테스트이 테스트에 방해가 될 수 있어서 일단 모두 주석처리해두었습니다. 해결되는대로 주석처리 풀도록 하겠습니다.
- 현재 develop 브랜치 test에 문제가 있는것으로 압니다. 그래서 pull은 따로 안받고 진행했습니다. 이 부분 해결되면 merge해서 충돌 처리해두겠습니다!

## 💬 리뷰 요구사항

 - 테이블 이렇게 하면 되겠죠?

2024-04-26 11:27 UTC, amaran-th requested changes
수고하셨습니다~! 몇군데 코멘트 남겼으니 반영 혹은 의견 부탁드릴게요!

2024-04-26 11:27 UTC, amaran-th commented on src/main/java/doore/member/api/MemberController.java
> +    public ResponseEntity<Void> transferTeamMaster(@PathVariable Long teamsId,
저희 팀에서 정한 용어사전의 표현을 사용해주시면 좋을 것 같아요!
프론트 측과 용어를 통일하면 소통하기 편하니까요:)
<img width="734" alt="image" src="https://github.com/BDD-CLUB/01-doo-re-back/assets/81465068/7ca339de-0c9b-43fa-92f5-e6580653127f">

2024-04-26 11:27 UTC, amaran-th commented on src/main/java/doore/member/api/MemberController.java
> +    public ResponseEntity<Void> transferTeamMaster(@PathVariable Long teamsId,
그리고 pathvariable 변수명은 의미에 맞게 teamId로 수정해주시는 편이 좋을 것 같습니다!

2024-04-26 11:27 UTC, amaran-th commented on src/main/resources/schema.sql
> +);
새로운 DDL은 sql 파일 맨 하단에 추가해주시는 게 좋을 것 같습니다!
운영서버에 배포하게 되면 schema.sql에 변경사항이 생길때마다 DDL sql문을 직접 실행시켜야해서, 언제 추가된 DDL인지 명확하게 알 수 있어야해서요!

2024-04-26 11:27 UTC, amaran-th commented on src/test/java/doore/document/application/DocumentCommandServiceTest.java
> +        @Disabled
앗 이부분은 제가 수정해서 PR을 올렸는데 테스트를 Disabled하는 것과 유지시키는 것 중 어느 쪽이 좋을지 고민해보신 뒤에 처리해주시면 감사할 것 같습니다!

2024-04-26 11:27 UTC, amaran-th commented on src/test/java/doore/restdocs/docs/MemberApiDocsTest.java
> +                .andDo(document("delete-member"));
RequestFieldsSnippet, ResponseFieldsSnippet 객체를 추가해주시면 프론트엔드 분들이 api 명세를 이해하기가 더 쉬워질 것 같아요~!

2024-04-26 11:27 UTC, amaran-th commented on src/main/java/doore/member/application/MemberCommandService.java
> +        validTeam(teamId);
메서드의 접두사는 동사형(validate)으로 짓는 것이 관례라고 합니다!
그리고 이름에서 Member/Team의 어떤 특성을 검증하는지도 드러낼 수 있다면 좋은 네이밍이 될 것 같아요!

2024-04-26 11:27 UTC, amaran-th commented on src/main/java/doore/member/domain/StudyRoleType.java
> +        this.id = id;
id가 어디에서 쓰이고 있는지 궁금합니다!

2024-05-01 14:27 UTC, JJimini commented on src/test/java/doore/document/application/DocumentCommandServiceTest.java
> +        @Disabled
저는 유지시키는게 좋아보입니다! 지금 Disabled 해둔 이유는 그냥 깔끔하게 테스트 성공이 나왔으면 좋겠어서 그랬습니다! 이 부분 수정사항 머지되면 풀면 될 것 같습니다!

2024-05-01 14:43 UTC, JJimini commented on src/main/java/doore/member/domain/StudyRoleType.java
> +        this.id = id;
현재 제 코드에서 가독성을 위해 쓰이지는 않고 있습니다만, id로도 간단하게 권한 체크가 가능해서 적어두었습니다. 근데 사실상 "1" 이렇게 id값을 작성하는 것보단 ROLE_** 이렇게 작성하는 것이 더 보기 편해서 잘 안쓰이긴 합니다..

2024-05-01 15:05 UTC, JJimini commented on src/test/java/doore/restdocs/docs/MemberApiDocsTest.java
> +                .andDo(document("delete-member"));
현재 MemberApiDocs에 있는 test들은 request와 response가 없어서 파라미터 설명 정도 추가해두었습니다!

2024-05-02 05:59 UTC, lcqff reviewed
수고하셨습니다👍👍👍 코드 보면서 저도 권한 동작 방식에 대해 공부를 많이 했네요!! 
간단한 내용들만 남겨뒀습니다!

2024-05-02 05:59 UTC, lcqff commented on src/main/java/doore/login/utils/AuthorizationExtractor.java
> +        request.setAttribute(ACCESS_TOKEN_TYPE, BEARER_TYPE);
Http 요청 헤더의 AuthorizationExtractor.ACCESS_TOKEN_TYPE 이라는 속성을 Bearer로 설정하는 거 맞나요?
왜 필요한 코드인지 궁금합니다!!

2024-05-02 05:59 UTC, lcqff commented on src/main/java/doore/login/utils/AuthorizationExtractor.java
> +
```suggestion
int commaIndex = authHeaderValue.indexOf(',');
int endIndex = (commaIndex > 0) ? commaIndex : authHeaderValue.length();
String authHeaderValue = authorizationHeader.substring(BEARER_TYPE.length(), endIndex).trim();
```

요렇게 하면 아래 If문 없앨수 있을 것 같습니다🤔

2024-05-02 05:59 UTC, lcqff commented on src/main/java/doore/member/application/MemberCommandService.java
> +        TeamRole checkTeamLeader = teamRoleRepository.findTeamRoleByTeamIdAndMemberId(teamId, memberId)
변수명을 동사가 아니라 명사로 하면 더 가독성이 좋아질 거 같아요~!
checkTeamLeader -> currentMemberTeamRole (혹은 더 나은 네이밍으로...)

2024-05-02 05:59 UTC, lcqff commented on src/main/java/doore/member/domain/TeamRole.java
> +    }
현재 메서드명에 '권한은 팀 리더와 팀원 두 개 뿐이다'라는 가정이 포함돼있는데 가정을 빼고 메서드 기능만을 표현하면 외부인이 보기에도 이해가 쉬울 것 같습니다! updateToTeamMember? 혹은 더 좋은...

2024-05-02 05:59 UTC, lcqff commented on src/main/java/doore/member/application/MemberCommandService.java
> +        previousTeamLeaderRole.updatePreviousTeamLeader();
위에서 memberId가 팀장 Role을 가지고 있음을 validate했으니 따로 팀장을 조회할 필요 없이 바로 checkTeamLeader를 사용하면 되지 않나요?? 혹시 제가 이해를 잘못하고 있는 부분 있으면 지적 부탁드립니다!

2024-05-02 05:59 UTC, lcqff commented on src/main/java/doore/member/domain/MemberDetails.java
> +public class MemberDetails implements UserDetails {
요런게 있군요~~~👀👀👀

2024-05-02 05:59 UTC, lcqff commented on src/main/java/doore/resolver/MemberArgumentResolver.java
> +    }
덕분에 공부가 많이됩니다😄😄

2024-05-02 05:59 UTC, lcqff commented on src/test/java/doore/member/MemberFixture.java
> +                .email("하지마@naver.com")
ㅋㅋㅋㅋㅋㅋㅋㅋ

2024-05-02 10:37 UTC, amaran-th approved these changes

2024-05-03 13:16 UTC, JJimini commented on src/main/java/doore/login/utils/AuthorizationExtractor.java
> +
이 부분은 `authHeaderValue`가 선언되기 전에 `commaIndex `쓰이고 있는 것 같아요...! 혹시 제가 잘못 이해했을 수도 있느니 회의시간에 이야기해보면 좋을 것 같아요!

2024-05-03 13:21 UTC, JJimini commented on src/main/java/doore/login/utils/AuthorizationExtractor.java
> +        request.setAttribute(ACCESS_TOKEN_TYPE, BEARER_TYPE);
해당 코드는 요청 객체에 `ACCESS_TOKEN_TYPE`이라는 속성을 추가하고 그 값으로 `BEARER_TYPE`으로 설정하는 코드입니다. 코드에서 해당 속성을 사용할 수 있도록 요청에 정보를 추가하는 겁니당! 저희는 토큰 타입이 `BEARER `타입이라서 다음과 같이 설정했습니다!

2024-05-03 13:22 UTC, JJimini commented on src/main/java/doore/member/application/MemberCommandService.java
> +        TeamRole checkTeamLeader = teamRoleRepository.findTeamRoleByTeamIdAndMemberId(teamId, memberId)
이 부분도 저희 convention에 맞게 행위를 나타내는 동사+명사 조합으로 설정했습니다!

2024-05-03 13:24 UTC, JJimini commented on src/main/java/doore/member/domain/TeamRole.java
> +    }
좋은 것 같습니다! 수정해두겠습니다~!

2024-05-03 13:24 UTC, JJimini commented on src/main/java/doore/member/application/MemberCommandService.java
> +        previousTeamLeaderRole.updatePreviousTeamLeader();
이 부분도 좋은 것 같습니당! 수정하겠습니다!

2024-05-03 13:38 UTC, merged