Feature/#113 텃밭 구현
BDD-CLUB/01-doo-re-back pull request #117
Opened 2024-05-10 08:19 UTC by lcqff

## #️⃣ 연관된 이슈

close #113 

## 📝 작업 내용

텃밭 데이터를 저장 및 조회하는 기능을 개발했습니다~
- 팀의 올해 텃밭 데이터 조회
- 학습자료 업로드/커리큘럼 체크시 텃밭 데이터 저장
- 학습자료 삭제/커리큘럼 체크해제시 텃밭 데이터 삭제

2024-05-23 05:33 UTC, JJimini requested changes
수고하셨습니다~! 리뷰가 늦어 죄송합니다ㅠㅠ comment 남겨두었으니 확인 부탁드립니다!

2024-05-23 05:33 UTC, JJimini commented on src/main/java/doore/garden/application/dto/response/DayGardenResponse.java
> +    public static DayGardenResponse of(LocalDate date, int contributeNumber) {
여기서 `contributeNumber`의 역할이 뭔가요??

2024-05-23 05:33 UTC, JJimini commented on src/main/java/doore/garden/application/dto/response/DayGardenResponse.java
> +        int dayOfWeek = date.getDayOfWeek().getValue() - 1;
0부터 시작하도록 설정하신 것 같은데 나중에 프론트분들께도 전달해주면 좋을 것 같아요!

2024-05-23 05:33 UTC, JJimini commented on src/main/java/doore/garden/api/GardenController.java
> +    }
```suggestion
        return ResponseEntity.ok(fullGardenResponse);
    }
```
간단하게 적을 수 있을 것 같아요!

2024-05-23 05:33 UTC, JJimini commented on src/main/java/doore/garden/application/GardenQueryService.java
> +    public List<DayGardenResponse>  getFullGarden(Long teamId) {
모든 정보를 가져온다는 의미라면 `getAllGarden`이라고 적어보는 건 어떨까요?? `Full`이 주는 느낌이 뭔가 가득찬? 이런 느낌인 것 같아서요..!

2024-05-23 05:33 UTC, JJimini commented on src/main/java/doore/garden/application/GardenQueryService.java
> +        return fullGardenResponse;
값이 할당되지 않은 변수를 사용하는 방법보단, stream을 사용하면 훨씬 간단하게 표현할 수 있을 것 같아요!

2024-05-23 05:33 UTC, JJimini commented on src/main/java/doore/garden/application/GardenCommandService.java
> +    public void createGarden(Document document) {
Nit : 사이에 개행이 있으면 더 좋을 것 같아요!

2024-05-23 05:33 UTC, JJimini commented on src/main/java/doore/garden/application/GardenCommandService.java
> +    public void deleteGarden(Document document) {
Nit: 여기도 개행이 있으면 더 좋을 것 같아요!

2024-05-23 05:33 UTC, JJimini commented on src/main/java/doore/garden/domain/ContributionGarden.java
> +public class ContributionGarden {
이 부분은 따로 클래스를 만들기보단, `Garden` class에 적는 것에 대해 어떻게 생각하시는지 궁금합니다!

2024-05-23 05:33 UTC, JJimini commented on src/main/java/doore/garden/domain/GardenType.java
> +    }
이 부분은` @RequiredArgsConstructor` 으로 생략할 수 있을 것 같아용

2024-05-23 05:33 UTC, JJimini commented on src/main/java/doore/garden/application/GardenCommandService.java
> +    public void createGarden(ParticipantCurriculumItem participantCurriculumItem) {
무엇에 의해서 생성되는 Garden인지 이름에 추가해주면 이해하기 더 쉬울 것 같습니다!

2024-05-23 05:33 UTC, JJimini commented on src/main/java/doore/garden/application/GardenCommandService.java
> +    private final GardenRepository gardenRepository;
여기 적힌 모든 메서드들이 `controller`와 연결되어 있지않고 기능만 정의하고 있는데, `GardenCommandService`에 적는것에 대해 팜님의 의견이 궁금합니다! 저는 각각 `DocumentCommandService`, `CurriculumCommandService`에서 처리하는 것이 더 좋아 보입니다! 

예를 들어 스터디 생성시 생성자를 스터디장으로 임명하는데, 스터디 생성은 `StudyCommandService`, 스터디장 임명은 `MemberCommandService`에서 진행하지 않는 것과 비슷합니다. (모두 `StudyCommandService`에서 처리함. 하나의 api이기 때문) 혹시 제가 이해한 것과 다른 의미의 코드라면 알려주세용! @lcqff

2024-05-23 05:33 UTC, JJimini commented on src/main/java/doore/garden/domain/repository/GardenRepository.java
> +}
👍👍

2024-05-23 05:33 UTC, JJimini commented on src/main/java/doore/study/api/CurriculumItemController.java
>          return ResponseEntity.noContent().build();
여기 불필요한 개행이 추가된 것 같습니당!

2024-05-23 05:33 UTC, JJimini commented on src/main/java/doore/study/application/CurriculumItemCommandService.java
> +        }
`return`은 불필요한 코드인 것 같습니다!

2024-05-23 05:33 UTC, JJimini commented on src/main/java/doore/study/application/CurriculumItemCommandService.java
> +            gardenCommandService.deleteGarden(participantCurriculumItem);
그런데 이 코드는 `participantCurriculumItem`이 체크되어있을때, `deleteGarden`을 하도록 설정하신건가요..??

2024-05-23 05:33 UTC, JJimini commented on src/test/java/doore/garden/application/GardenCommandServiceTest.java
> +    CurriculumItemCommandService curriculumItemCommandService;
접근제어자와 개행 신경써주시면 좋을 것 같습니다! 이 코드 외 다른 코드들은  권한 부여할 때 다 수정해두어서 `GardenTest` 쪽만 수정해주시면 될 것 같습니당!

2024-05-23 05:33 UTC, JJimini commented on src/test/java/doore/garden/application/GardenCommandServiceTest.java
> +public class GardenCommandServiceTest extends IntegrationTest {
`Service` 코드의 위치가 수정된다면, 이 부분도 각각의 `ServiceTest`에 작성해주시면 될 것 같습니다😄

2024-05-23 05:33 UTC, JJimini commented on src/test/java/doore/garden/application/GardenCommandServiceTest.java
> +        gardenCommandService.createGarden(participantCurriculumItem);
이 테스트는 잘못된 것 같습니다! 커리큘럼 체크 시 정상적으로 텃밭을 생성한다면, 커리큘럼 체크를 호출하고, 그것이 `true`일때 `createGarden`이 호출되고, `GardenRepository`에 정상 저장되어있는지 테스트해보아야할 것 같습니다! 지금 테스트는 바로 `createGarden`을 호출하기 때문에 커리큘럼이 체크되어서 `Garden`이 생성되었는지 인과관계를 확인하기 어려운 것 같습니다😃😃

2024-05-23 05:33 UTC, JJimini commented on src/test/java/doore/garden/application/GardenCommandServiceTest.java
> +        gardenCommandService.createGarden(document);
윗 코멘트와 동일합니다!

2024-05-23 05:33 UTC, JJimini commented on src/test/java/doore/garden/application/GardenCommandServiceTest.java
> +    public void deleteGarden_커리큘럼_체크_해재시_정상적으로_텃밭에_반영된다_성공() throws Exception {
오타인것같습니당~!

2024-05-23 05:33 UTC, JJimini commented on src/test/java/doore/garden/application/GardenCommandServiceTest.java
> +        gardenCommandService.deleteGarden(participantCurriculumItem);
이 부분도 `createGarden`을 하면 생성되고 `deleteGarden`을 하면 삭제되는 코드여서 커리큘럼이 해제되어 삭제되었는지 확인하기 어려운 것 같습니다~!

2024-05-27 04:11 UTC, lcqff commented on src/main/java/doore/garden/application/dto/response/DayGardenResponse.java
> +    public static DayGardenResponse of(LocalDate date, int contributeNumber) {
해당 날짜에 총합 몇개의 기여가 이루어졌는지에 대한 필드입니다!
ex) 학습자료 업로드 2번, 커리큘럼 체크 3번 => 5번의 기여
contributeCount가 더 좋을까요?

2024-05-27 04:11 UTC, lcqff commented on src/main/java/doore/garden/application/dto/response/DayGardenResponse.java
> +        int dayOfWeek = date.getDayOfWeek().getValue() - 1;
프론트는 이미 3d 잔디 기능이 만들어져 있어서 프론트에게 먼저 여쭙고 만들었습니다😄👍

2024-05-27 04:11 UTC, lcqff commented on src/main/java/doore/study/application/CurriculumItemCommandService.java
> +        }
아래 createGarden 실행을 피하려고 return했습니다!

2024-05-27 04:11 UTC, lcqff commented on src/test/java/doore/garden/application/GardenCommandServiceTest.java
> +        gardenCommandService.createGarden(participantCurriculumItem);
아아... 이부분....😄
테스트 코드명을 수정하는걸 깜빡한 것 같습니다!
처음에는 테스트코드 명과 동일하게 커리큘럼 체크 호출 -> 커리큘럼 체크가 true임을 확인 -> CreateGarden이 실행됨을 가정 -> Garden이 데이터베이스에 저장되었음을 확인
과 같은 흐름으로 테스트를 진행하려 했으나... 위와 같이 테스트하기엔 ParticipantCurriculumItem과 연결된 엔티티들이 너무 많았습니다...😵‍💫

제가 사용했던 기존 테스트 코드는 아래와 같습니다
```java
//given
CurriculumItem curriculumItem = curriculumItem();
curriculumItemRepository.save(curriculumItem);
Long curriculumItemId = 1L;
Long participantId = 1L;
ParticipantCurriculumItem participantCurriculumItem = ParticipantCurriculumItem.builder()
      .participantId(participantId)
      .curriculumItem(curriculumItem)
      .build();
participantCurriculumItemRepository.save(participantCurriculumItem);

//when
when(participantRepository.findById(anyLong())).thenReturn(Optional.of(mock(Participant.class)));
curriculumItemCommandService.checkCurriculum(curriculumItem.getId(), participantId);

//then
Garden garden = gardenRepository.findAll().get(0);
assertEquals(garden.getType(), GardenType.COMPLETE_STUDY_CURRICULUM);
assertEquals(garden.getContributionId(), participantCurriculumItem.getId());
``` 

실제 데이터베이스에 값을 저장할수도 있었겠지만 메서드 하나를 테스트하기 위해 curriculumItem, participant, member, participantCurriculumItem(이거는 결과값을 비교하기 위해 필수적으로 생성)의 4개의 데이터를 레포에 저장해야하는 과정이 비효율적이라 여겨졌습니다😥 

mock을 통해 checkCurriculum의 `findByCurriculumItemIdAndParticipantId` 메서드를 넘기기엔 결과값 비교를 위해 ParticipantCurriculumItem가 @Autowired 처리가 되어있었기 때문에 mock 선언이 불가능했습니다😭

고민한 결과 실제 레포에 저장됐음을 테스트할 필요 없는 participant등을 모두 레포에 저장하기보단 GardenCommandServiceTest에서는 create,deleteGarden 메서드만 테스트하고 
checkCurriculum 메서드를 통한 createGarden/deleteGarden 호출 여부는 CurriculumTest로 테스트 의존성?을 분리함이 옳다고 판단했습니다! (이 테스트 코드는... 귀찮아서 작성 안한것이 맞긴합니다😅)

특정 데이터를 직접 데이터베이스에 저장하여 테스트해야할때 해당 데이터와 의존관계에 있는 다른 데이터들을 어떻게 기깔나게 처리할지에 대해서는 아직도 고민이 많습니다...🤔 미나님도 다른 아이디어나 의견이 있으시다면 듣고싶습니다!!

2024-05-27 04:11 UTC, lcqff commented on src/main/java/doore/garden/application/GardenCommandService.java
> +    private final GardenRepository gardenRepository;
저도 이 부분에 대해서 고민했었는데 이후 garden을 생성하는 요소가 확장될 경우 garden을 생성하는 코드를 모아두는 편이 기능 이해에 더 도움이 될 것 같아 따로 서비스를 만들었습니다.
그러나 미나님 말씀을 들어보니 Controller와 연결되어 있지 않은 것도 좀 걸리고, 기존 코드의 메서드들도 모두 역할에 따라 구분되어 있으니 분리하는 편이 통일성에도 더 좋아보입니다🤔 🤔  찬성입니다~~~

2024-05-27 04:11 UTC, lcqff commented on src/main/java/doore/garden/domain/ContributionGarden.java
> +public class ContributionGarden {
좋은것 같습니다👀👀👀

2024-05-27 04:11 UTC, lcqff commented on src/main/java/doore/study/application/CurriculumItemCommandService.java
> +            gardenCommandService.deleteGarden(participantCurriculumItem);
으음~~~~???? 그러게요😅 제일 마지막에 해당 코드를 수정했던걸로 아는데 수정이 안된건지 애초에 수정을 이상하게 한건지 모르겠네요 하핫,, 수정하겠습니다!

2024-05-31 10:17 UTC, JJimini commented on src/main/java/doore/garden/application/dto/response/DayGardenResponse.java
> +    public static DayGardenResponse of(LocalDate date, int contributeNumber) {
그렇군요! 저는 횟수를 센다는 의미해서 `contributeCount`가 더 이해하기 쉬울 것 같습니다!

2024-05-31 10:42 UTC, JJimini commented on src/test/java/doore/garden/application/GardenCommandServiceTest.java
> +        gardenCommandService.createGarden(participantCurriculumItem);
팜님이 생각하신 부분 잘 읽었습니다! 이 부분의 테스트 코드 작성이 길어진 이유는 앞선 코멘트와 같이 CurriculumService의 내용이 gardenService로 작성되어서 그런 것 같습니다. 이미 `CurriculumCommandServiceTest`에 `checkCurriculum`에 대한 테스트가 작성되어있고, 그 코드의 내용을 참고하여 `checkCurriculum`이 `true`가 되었을 떄, `garden`에 대한 내용이 저장되는지 확인하면 될 것 같습니다!

커리큘럼 테스트에 대한 부분은 제가 작성한 부분이라 수정이 더 쉬울 것 같은데, 괜찮으시면 `gardenCommandServiceTest`에 대한 내용은 삭제하고(`gardenCommandService`가 사라졌기 때문), `merge`한 후 제가 해당 테스트 부분을 추가해도 될까요?? @lcqff

2024-05-31 10:44 UTC, JJimini approved these changes
남은 부분들은 사소한 부분들 인 것 같아 미리 approve 해두겠습니다~!

2024-05-31 12:17 UTC, lcqff commented on src/test/java/doore/garden/application/GardenCommandServiceTest.java
> +        gardenCommandService.createGarden(participantCurriculumItem);
좋습니다~! 현재 curriculumItemServiceTest쪽에 CurriculumGardenTest라는 이름으로 기존 garden 테스트들 옮겨놓은 상태입니다!

2024-05-31 12:18 UTC, lcqff commented on src/test/java/doore/garden/application/GardenCommandServiceTest.java
> +        gardenCommandService.createGarden(participantCurriculumItem);
좋습니다~ 기존 GardenTest들은 CurriculumItemServiceCommandTest쪽으로 옮겨놓은 상태입니다! (참고용으로 말씀드려요) @JJimini

2024-05-31 12:24 UTC, merged