Feature/#110 권한 설정이 필요한 모든 코드를 수정한다
BDD-CLUB/01-doo-re-back pull request #123
Opened 2024-05-22 14:44 UTC by JJimini

## #️⃣ 연관된 이슈

 close: #110

## 📝 작업 내용

- `MemberTeam`을 제외한 모든 코드에 권한 작업을 하였습니다.

## 💬 리뷰 요구사항

- 각각 부여한 권한은 `controller`에 주석으로 적어두었습니다. 확인 후 merge 전 주석은 삭제하도록 하겠습니다.
- `MemberTeam`은 로직을 고쳐야해서 다른 pr로 작업할 예정입니다.
- `스터디 삭제 시 커리큘럼 삭제`도 다른 pr로 작업할 예정입니다.
- 참여자 test에 모두 `findAllParticipant`을 테스트하고 있던데 확인 부탁드립니다. @lcqff 
- 모든 코드를 고치다 보니 빠진 부분이나 잘못된 부분이 있을 수 있습니다. 혹시 있다면 리뷰 부탁드립니다!

2024-05-28 17:37 UTC, lcqff requested changes
권한 부여하려면 코드 전체적으로 다 살펴보셔야 하셨을텐데 정말 수고 많으셨습니다!! 
코드 리뷰 늦어서 죄송합니다(ㅠㅠ)
일부 정보들은 비회원에게도 조회 가능하도록 해야할것 같은데 이 부분에 대해서는 정확히 얼마나 노출할지 말을 맞춰보고 수정하는 걸로 해요
실제 권한이랑 맞지 않은 부분들 몇개만 리뷰 남겨두었습니다!

2024-05-28 17:37 UTC, lcqff commented on src/main/java/doore/document/api/DocumentController.java
> +    @DeleteMapping("/{documentId}") // 회원
회원 + 해당 자료를 업로드한 사람만 삭제 가능하도록 해야할 것 같습니다!

2024-05-28 17:37 UTC, lcqff commented on src/main/java/doore/document/api/DocumentController.java
>      public ResponseEntity<Void> updateDocument(@Valid @RequestBody DocumentUpdateRequest request,
회원 + 해당 자료를 업로드한 사람만 수정 가능하도록 해야할 것 같습니다!

2024-05-28 17:37 UTC, lcqff commented on src/main/java/doore/study/api/ParticipantController.java
> +    public ResponseEntity<Void> withdrawParticipant(@PathVariable Long studyId, @LoginMember Member member) {
이거는 회원 탈퇴 기능이라 스터디장이 아닌 회원쪽 권한인것 같습니다!

2024-05-30 02:17 UTC, JJimini commented on src/main/java/doore/study/api/ParticipantController.java
> +    public ResponseEntity<Void> withdrawParticipant(@PathVariable Long studyId, @LoginMember Member member) {
회원 탈퇴 기능은 Member쪽에 따로 있는걸로 알고 있습니다! 저희가 Participant를 스터디원으로 정의했기 때문에 스터디원 탈퇴..? 거절...? 기능쪽으로 이해했습니다!

2024-05-30 06:30 UTC, lcqff commented on src/main/java/doore/study/api/ParticipantController.java
> +    public ResponseEntity<Void> withdrawParticipant(@PathVariable Long studyId, @LoginMember Member member) {
앗 제가 말을 이상하게 했네요😅 
deleteParticipant -> 참여자 삭제 기능 (스터디장 권한)
withdrawParticipant -> 참여자 탈퇴 기능 (참여자 권한) 이라는 의미였습니다~~~!

2024-05-30 07:34 UTC, JJimini commented on src/main/java/doore/study/api/ParticipantController.java
> +    public ResponseEntity<Void> withdrawParticipant(@PathVariable Long studyId, @LoginMember Member member) {
아 넵넵 확인했습니다~! 수정하겠습니다!

2024-05-31 14:55 UTC, lcqff approved these changes

2024-05-31 15:16 UTC, merged