Feature/#124 팀 삭제 시 연관된 스터디와 커리큘럼도 삭제된다
BDD-CLUB/01-doo-re-back pull request #132
Opened 2024-06-03 07:49 UTC by JJimini

## #️⃣ 연관된 이슈
close: #124

## 📝 작업 내용
- 팀이 삭제되면 스터디, 커리큘럼, 참여자 커리큘럼이 삭제됩니다.
- 스터디가 삭제되면 커리큘럼, 참여자 커리큘럼이 삭제됩니다.
- 커리큘럼이 삭제되면 참여자 커리큘럼이 삭제됩니다.

## 💬 리뷰 요구사항(선택)
- 원래 있던 코드는 그대로 두고, 이번 작업 내용만 soft Delete로 작성하였습니다. 다른 코드는 #98 에서 해결하는게 작업 단위가 맞을 것 같습니다!

2024-06-05 10:07 UTC, lcqff requested changes
하하... 맞습니다... s3... 문제가 있더군요😭 인프라쪽 문제같아서 빨리 해결을 하겠습니다
커리큘럼 삭제 관련해서 리뷰 남겨놨습니다!!

2024-06-05 10:07 UTC, lcqff commented on src/main/java/doore/study/domain/ParticipantCurriculumItem.java
> +@SQLDelete(sql = "UPDATE ParticipantCurriculumItem SET is_deleted = true where id = ?")
👍

2024-06-05 10:07 UTC, lcqff commented on src/main/java/doore/study/domain/Study.java
> +    public void isDelete() {
isDelete보다는 delete로 메서드명 권유드려봅니다🤔

2024-06-05 10:07 UTC, lcqff commented on src/main/java/doore/study/application/StudyCommandService.java
> +        });
수료증 기능 관련해서 의논해봐야 할 부분이 있을것 같습니다😥
수료증에 포함된 커리큘럼은 따로 데이터를 저장하는게 아니라 기존의 데이터를 가져오는 식으로 기획되어? 아니면 저혼자 생각을 해보았었는데 이렇게 되면 어떤 커리큘럼이 스터디 진행중에 스터디장이 삭제한 커리큘럼인지, 아니면 스터디나 팀이 삭제되어 함께 삭제된 커리큘럼인지 구분할수가 없을 것 같습니다.

생각을 해보았는데 
1. 팀과 스터디 삭제시 커리큘럼은 따로 삭제처리 x(is deleted=false로 유지)
2. 스터디 진행중 스터디장이 커리큘럼 삭제하는 내역만 하드 delete 처리 (is_deleted=false값은 모두 스터디나 팀이 삭제되어 삭제된 커리큘럼이 됨)
3. 수료증 테이블을 만들어 수료증 생성 시점에 스터디의 데이터들을 따로 저장

이정도의 방법이 있어보이는데 미나님의 의견이 궁금합니다🤔

2024-06-05 10:07 UTC, lcqff commented on src/main/java/doore/team/application/TeamCommandService.java
> +                participantCurriculumItems.forEach(ParticipantCurriculumItem::isDelete);
deleteStudy 쪽에 남긴 리뷰 참고부탁드립니다!

2024-06-05 12:49 UTC, JJimini commented on src/main/java/doore/study/domain/Study.java
> +    public void isDelete() {
음.. 원래는 true와 false를 다룬다는 점에서 isDelete라는 이름으로 작성하였었는데, 저희는 true인지 false인지 "판단"목적이 아닌, soft delete를 하며 "삭제"목적으로만 해당 메서드를 사용할 예정이니 메서드명을 변경하는 것도 좋아보입니다!

2024-06-05 13:08 UTC, JJimini commented on src/main/java/doore/study/application/StudyCommandService.java
> +        });
팜님의 의견을 정리해보면 수료증 기능을 만들때, 데이터를 불러오는 과정에서 스터디장이 삭제한 커리큘럼은 조회가 되지 않아야하고, 팀과 스터디가 삭제된 경우에 삭제된 커리큘럼은 조회가 되어야 한다는 것 같습니다! (제가 이해를 잘못한거라면 알려주세요)

제 생각은,
1. 서비스가 계속 유지보수하며 이어진다고 가정하였을 때, 사람들이 많이 헷갈릴 것 같습니다.
2. 저는 이 방법이 좋아보입니다. 저희가 데이터를 보호하기 위헤 soft delete를 하자고 결정하였지만, 스터디장이 삭제하는 커리큘럼 데이터는 상대적으로 중요도가 낮아보입니다. 그리고 is_delete = true이면 스터디 or 팀이 삭제되어 삭제된 커리큘럼으로 판단하는 것이 맞아보입니다!
3. 스터디 데이터가 적지 않은데 이것 또한 DB부하가 생길 것 같습니다!

2024-06-07 06:20 UTC, lcqff commented on src/main/java/doore/study/application/StudyCommandService.java
> +        });
좋습니다~~~ 2번 방향으로 가고 이슈 따로 파서 처리하는 걸로 하죠!

2024-06-07 06:22 UTC, lcqff approved these changes
수고하셨습니다!!

2024-06-07 07:00 UTC, merged