Feature/#127 팀 상세 조회 기능 구현
BDD-CLUB/01-doo-re-back pull request #134
Opened 2024-06-05 05:22 UTC by JJimini

## #️⃣ 연관된 이슈

close: #127 

## 📝 작업 내용
- 팀 상세보기를 구현했습니다.
- 잔디와 팀원은 조회에서 제외해달라고 하셔서 넣지 않았습니다!

## 💬 리뷰 요구사항(선택)
- 확인해보시고 팀에 이것말고 더 조회되어야할 부분 알려주세요!

2024-06-05 10:41 UTC, lcqff requested changes
RESTDOCS 관련해서 간단한 리뷰 하나 남겼습니다!

2024-06-05 10:41 UTC, lcqff commented on src/main/java/doore/team/application/TeamQueryService.java
> +        long attendanceRatio = countMemberTeam > 0 ? (long)((countAttendanceMemberTeam * 100.0) / countMemberTeam) : 0;
👍👍

2024-06-05 10:41 UTC, lcqff commented on src/main/java/doore/attendance/domain/repository/AttendanceRepository.java
> +    List<Attendance> findAllByMemberIdIn(List<Long> memberIds);
In이 무슨 뜻일까요??

2024-06-05 10:41 UTC, lcqff commented on src/test/java/doore/restdocs/docs/TeamApiDocsTest.java
> +                .andDo(document("get-team", pathParameters, responseFieldsSnippet));
PathVariable 설명은 있는 편이 좋을 거 같아요~!

2024-06-05 13:12 UTC, JJimini commented on src/main/java/doore/attendance/domain/repository/AttendanceRepository.java
> +    List<Attendance> findAllByMemberIdIn(List<Long> memberIds);
SQL의 In 절을 의미합니다! `memberIds `리스트에 포함된 여러 `memberId `값들에 해당하는 모든 `Attendance `객체를 찾아 온다는 의미입니다! 만약 In이 없다면 단일 `memberId`에 대해서만 조회한다는 의미가 됩니다!

2024-06-05 13:18 UTC, JJimini commented on src/test/java/doore/restdocs/docs/TeamApiDocsTest.java
> +                .andDo(document("get-team", pathParameters, responseFieldsSnippet));
혹시 pathParameters 말씀하시는 건가요?? 그 부분은 이미 작성되어 있습니다!

2024-06-07 06:23 UTC, lcqff approved these changes

2024-06-07 06:23 UTC, lcqff commented on src/main/java/doore/attendance/domain/repository/AttendanceRepository.java
> +    List<Attendance> findAllByMemberIdIn(List<Long> memberIds);
오호~ 알겠습니다!

2024-06-07 06:23 UTC, lcqff commented on src/test/java/doore/restdocs/docs/TeamApiDocsTest.java
> +                .andDo(document("get-team", pathParameters, responseFieldsSnippet));
헉 그러게요😅 짱입니다~

2024-06-07 07:01 UTC, merged