Feature/#130 비회원 관련 권한 수정
BDD-CLUB/01-doo-re-back pull request #135
Opened 2024-06-05 07:31 UTC by JJimini

## #️⃣ 연관된 이슈

close: #130 

## 📝 작업 내용

- 비회원 관련 권한을 수정하였습니다.
    - 비회원은 팀 페이지 + 스터디 페이지 + 팀 학습자료까지 조회가 가능합니다.
    - 스터디 구성원만이 스터디 학습자료 조회가 가능합니다.

## 💬 리뷰 요구사항(선택)

- 팀 페이지 권한 수정은 팀 상세보기 pr이 머지되면 pull 받아서 합쳐두겠습니다! (이미 팀 상세보기는 비회원 권한으로 작성되어있음)

2024-06-05 10:56 UTC, lcqff requested changes
학습자료 목록은 비회원도 조회 가능한편이 좋지 않을까 싶습니다!
슬랙에서 디엠할때 얘기드렸으면 좋았을텐데 그때는 학습자료 조회쪽으로 생각하고있어서 말씀을 못드렸네요ㅠㅠ 죄송합니다

2024-06-05 10:56 UTC, lcqff commented on src/main/java/doore/document/application/DocumentQueryService.java
>              DocumentGroupType groupType, Long groupId, Pageable pageable, Long memberId) {
비회원이라 member가 null로 들어와도 getId()할때 오류 안나나요??😯

2024-06-05 10:56 UTC, lcqff commented on src/main/java/doore/document/application/DocumentQueryService.java
>              DocumentGroupType groupType, Long groupId, Pageable pageable, Long memberId) {
생각해보니 getAllDocument는 목록 조회인데 (실제 학습자료 데이터는 조회되지 않음) 이 부분은 비회원이 조회 못할 이유가 없을거 같기도...😅 그리고 비회원이 페이지에 접속했을때 학습자료 목록 조회가 안되면 텅텅 비어보여서 ui상으로도 예쁘지 않을 거 같아요ㅠ

2024-06-05 10:56 UTC, lcqff commented on src/main/java/doore/study/api/StudyController.java
> +        StudyResponse studyDetailResponse = studyQueryService.findStudyById(studyId);
👍

2024-06-05 13:26 UTC, JJimini commented on src/main/java/doore/document/application/DocumentQueryService.java
>              DocumentGroupType groupType, Long groupId, Pageable pageable, Long memberId) {
groupType이 STUDY인 경우에만 memberId를 사용하기 때문에 NPE는 나지 않습니다. 목록 조회는 저도 비회원으로 하는것이 좋아보입니다. getDocument에 권한을 부여해야겠네요~

2024-06-07 06:25 UTC, lcqff approved these changes

2024-06-07 07:06 UTC, merged