Feature/#151 나의 스터디 조회 response 변경
BDD-CLUB/01-doo-re-back pull request #152
Opened 2024-06-21 09:44 UTC by JJimini

## #️⃣ 연관된 이슈

close: #151 

## 📝 작업 내용

- 나의 스터디 조회 response를 StudySimpleResponse에서 StudyResponse로 변경하였습니다.
- 스터디 조회 테스트 오류를 수정하였습니다.

2024-06-21 12:57 UTC, lcqff requested changes
간단한 리퀘스트 체인지 하나 남겼습니다!
추가로 그럼 개발 서버에서의 스터디 조회 오류는 해결 된 걸까요??

2024-06-21 12:57 UTC, lcqff commented on src/main/java/doore/study/application/StudyQueryService.java
> +                        cropRepository.findById(study.getCropId()).orElse(null)))
StudyResponse.of() 메서드를 통해 넘어온 Crop와 Team을 사용하여 CropReference와 TeamReference가 생성되게 되는데 이때 넘어오는 값이 null이라면 문제가 생길 거 같아요!
orElse시 예외를 발생시키는게 좋을 것 같습니다!

2024-06-21 13:24 UTC, JJimini commented on src/main/java/doore/study/application/StudyQueryService.java
> +                        cropRepository.findById(study.getCropId()).orElse(null)))
그렇겠네요! null이 들어가면 안되겠네요! 수정해두겠습니다~

2024-06-21 13:30 UTC, JJimini commented
조회 테스트 오류는 프론트 측에서 연결해봐야 알 것 같습니다.. (아직 안하신 걸로 알고 있습니다!)
지난번 회의에서는 저희 test가 통과를 못해서 저희 문제일 수 있다고 말했던 것 같은데,
본 코드는 고치지 않고 test만 고치고 통과가 되어서(단순 코드 오류 - 타입 오류), 실제 개발 서버는 달라진 부분이 없을 것 같습니다..  프론트 측에서도 4xx 에러라고 했던 것 같은데, 이제 저희 문제가 아닌 것 같기두...

2024-06-21 13:34 UTC, lcqff commented
> 조회 테스트 오류는 프론트 측에서 연결해봐야 알 것 같습니다.. (아직 안하신 걸로 알고 있습니다!)
> 지난번 회의에서는 저희 test가 통과를 못해서 저희 문제일 수 있다고 말했던 것 같은데,
> 본 코드는 고치지 않고 test만 고치고 통과가 되어서(단순 코드 오류 - 타입 오류), 실제 개발 서버는 달라진 부분이 없을 것 같습니다.. 프론트 측에서도 4xx 에러라고 했던 것 같은데, 이제 저희 문제가 아닌 것 같기두...

에러가 터져서 아직 연결을 못하셨다고 기억하고 있습니다! 가능하시다면 포스트맨으로 정확히 어떤 문제인지 확인 부탁드려도 될까요?
백엔드쪽 문제가 맞다면 해당 PR은 닫고 새로 조회 오류 해결 이슈 파서 처리해도 될 것 같습니다!

2024-06-21 14:08 UTC, JJimini commented
제 생각은... 백엔드 문제가 아닌 것 같습니다,, 저희는 api 호출이 정상적으로 되어 docs에도 정상적으로 뜨기 때문에 포스트맨 호출하면 docs내용과 똑같이 정상적으로 뜰 것 같습니다! 그리고 `나의 팀 조회`는 포스트맨 호출하려면 토큰이 필요한데, 저희가 admin 계정도 없고, 소셜 로그인밖에 없어서 토큰을 받기가 어려울 것 같습니다...ㅠㅠ
제 생각엔 여기서 error가 날 부분이 토큰 밖에 없을 것 같은데, 이 pr은 테스트 오류가 나지 않으니 닫고, 그냥 제가 개인적으로 (branch 만들지 않고) 도리님과 이야기하며 이것 저것 건드려 보는 게 제일 좋을 것 같습니다..
또한 나의 팀 조회 api가 정상적으로 연결된다면 더욱 백엔드 쪽 문제는 아닐 것 같습니다..(로직이 똑같기 때문)

2024-06-21 14:13 UTC, JJimini commented
그런데 생각해보니 저희 테스트만 바뀐게 아니라 스터디 조회 코드가 완전 바뀌었군요?! 그렇다면.. 프론트 측에서 오류가 안날 수도 있겠는데요...!

2024-06-21 15:29 UTC, lcqff approved these changes
수고하셨습니다! 제가 스터디 조회에서 오류있다는 말을 하필 나의 스터디 조회 PR에서 해버려서 헷갈리게 만들어버렸네요😂 죄송합니다... 스터디 조회 오류 해결은 따로 PR 올려주시면 감사하겠습니다!!

2024-06-22 07:35 UTC, JJimini commented
아하아하 저도 헷갈리게 말한 것 같네요~! 일단 스터디 조회는 따로 걸린 권한이 없으니 확인해보겠습니다!

2024-06-22 07:37 UTC, merged