Feature/#19-CORS 설정
BDD-CLUB/01-doo-re-back pull request #26
Opened 2024-01-21 09:52 UTC by lcqff

#19

## #️⃣ 연관된 이슈

close: #19

## 📝 작업 내용
> CORS(Cross-Origin Resource Sharing)
웹 브라우저에서 발생하는 보안 정책 중 하나로, 웹 브라우저가 다른 도메인(Origin)의 리소스에 접근할 수 있도록 하는 설정
웹 브라우저가 기본적으로 따르는 동일 출처 정책으로 인해 다른 출처에서 온 리소스의 접근을 차단되기 때문에 발생

CORS를 설정했습니다.
origin이랑 methods는 yml파일 내에 따로 설정해뒀습니다.

`origin`: http://localhost:3000
`method`: 로컬 환경에서의 사용을 염두로 두어 일단 HTTP 메서드 전부다 추가해두었습니다.
`header`: 웹 브라우저의 기본 허용 대상인 "Origin", "Content-Type", "Accept"와 JWT 토큰 사용을 위해 "Authorization"를 추가해두었습니다.
`credentials`: 클라이언트 측에 대한 응답에 자격증명(쿠키, 인증 헤더...)을 포함하게 설정해뒀습니다. 이 부분에 있어서는 보안 문제가 발생할 수도 있다는데 일단 개발 서버에서 사용할거니까... 

## 💬 리뷰 요구사항(선택)

필요 없는 부분이 있거나 필요한데 빠진 설정이 있다면 알려주세요~!

2024-01-23 00:50 UTC, 02ggang9 approved these changes
리뷰를 늦게 드렸네용.. 작성하신다고 수고 많으셨습니다~~ 👍👍

2024-01-23 15:19 UTC, amaran-th requested changes
수고하셨습니다~!
의견 몇 개 남겼는데 확인 부탁드려요!

2024-01-23 15:19 UTC, amaran-th commented on src/main/java/doore/config/WebConfig.java
> +                .allowedMethods(allowedMethods)
개인적으로 이 부분은 "*"로 넣어줘서 모든 메서드를 허용하도록 하는 편이 더 간단할 것 같아요~!

2024-01-23 15:19 UTC, amaran-th commented on src/main/resources/application.yml
> +      - "http://localhost:3000"
굿입니다~

2024-01-23 15:19 UTC, amaran-th commented on src/main/java/doore/config/WebConfig.java
> +public class WebConfig implements WebMvcConfigurer {
앞으로 하나의 Config 파일을 사용할지, 용도에 따라 Config 파일을 나눠서 사용할지 논의가 필요할 것 같네요...! 후자의 경우 필요한 구성 설정을 찾기가 쉬워서 제가 선호하는 방법입니다.
만약 후자대로 한다고 했을 때, WebConfig보다는 CorsConfig가 좀 더 직관적일 것 같아서 의견 남겨요!

2024-01-23 19:28 UTC, lcqff commented on src/main/java/doore/config/WebConfig.java
> +                .allowedMethods(allowedMethods)
모든 HTTP 메서드를 허용해도 되는가에 대해 걱정이 되어 검색을 하다가 Cors 허용에 대해 와일드카드를 사용하는 경우에 대한 글을 몇개 발견했는데요~! 
<img width="762" alt="image" src="https://github.com/BDD-CLUB/01-doo-re-back/assets/71930280/92fd4ba0-1f13-4ba2-9432-ac27a518d8a7">
[위 문서](https://developer.mozilla.org/ko/docs/Web/HTTP/Headers/Access-Control-Allow-Methods)를 보면 몇 브라우저에서는 access-control-allow-methods에 와일드카드를 사용하는 것에 대해 호환이 안되는 것 같아 보입니다🤔

2024-01-23 19:28 UTC, lcqff commented on src/main/java/doore/config/WebConfig.java
> +public class WebConfig implements WebMvcConfigurer {
좋습니다~

2024-01-24 01:10 UTC, shkisme approved these changes
👍~~~ 수고하셨습니당

2024-01-24 06:06 UTC, JJimini approved these changes
확인했습니다~ 수고하셨습니다

2024-01-24 11:02 UTC, amaran-th commented on src/main/java/doore/config/WebConfig.java
> +                .allowedMethods(allowedMethods)
아하...저도 처음 알았네요...!
그럼 OPTION 메서드만 추가해주실 수 있을까요~??
추후 권한 관련해서 구현할 때 CORS에 걸릴 것 같아서요!

2024-01-24 11:03 UTC, lcqff commented on src/main/java/doore/config/WebConfig.java
> +                .allowedMethods(allowedMethods)
알겠습니당~!

2024-01-24 12:52 UTC, amaran-th approved these changes

2024-01-26 03:37 UTC, merged