Feature/#20 참여자 crud 기능 구현
BDD-CLUB/01-doo-re-back pull request #61
Opened 2024-01-31 04:58 UTC by lcqff

## #️⃣ 연관된 이슈

close: #20

## 📝 작업 내용

- 참여자 추가
- 참여자 삭제
- 참여자 탈퇴
- 참여자 목록 조회

## 💬 리뷰 요구사항(선택)

레파지토리 테스트 이렇게 하는게 맞는지 모르겠네요~~~~!!
문서 테스트에서 조회 테스트시 responseBody가 왜 비어서 나오는지는 아직도 모르겠습니다............ 분명 postman에서는 제대로 나오는데 말이죠

스터디CRUD 할 때 service 테스트를 분리 안했어서 이번 PR하면서 분리했는데 그래서 변경사항에 스터디 Service 테스트 코드가 같이 잡혔습니다. 아래로 내려서 참여자 테스트 코드만 확인해주시면 됩니다  

## ⏰ 예상했던 소요시간/실제 소요시간(선택)

5시간 / 9시간?

2024-02-01 06:01 UTC, amaran-th requested changes
구현하시느라 수고하셨습니다~~!
테스트쪽에 확인해주셔야 하는 부분이 있어서 RC 남깁니다...!

2024-02-01 06:01 UTC, amaran-th commented on src/main/java/doore/study/application/StudyCommandService.java
> +        checkExistStudy(studyId);
사소하긴 한데 명사와 동사 둘 다 사용되는 check보다는 명확하게 동사형인 validate를 사용하는 것은 어떨까요~?

2024-02-01 06:01 UTC, amaran-th commented on src/main/java/doore/study/api/StudyController.java
> +    public ResponseEntity<Void> withdrawParticipant(@PathVariable Long studyId, HttpSession session) {
혹시 HttpSession은 왜 불러오는 건가요??

2024-02-01 06:01 UTC, amaran-th commented on src/test/java/doore/member/domain/repository/ParticipantRepositoryTest.java
> +        );
검증 로직을 아래 코드처럼 수정해보는 것은 어떤가요??
usingRecursiveComparison()을 사용하면 리스트, 객체도 비교할 수 있어요~

```java
final List<Participant> expectedParticipants = List.of(participant1, participant2);
assertThat(participants)
    .usingRecursiveComparison()
    .isEqualTo(expectedParticipants);
```

2024-02-01 06:01 UTC, amaran-th commented on src/test/java/doore/member/domain/repository/ParticipantRepositoryTest.java
> +        em.clear();
이 코드가 없으면 어떤 일이 생기나요?

2024-02-01 06:01 UTC, amaran-th commented on src/test/java/doore/restdocs/docs/StudyApiDocsTest.java
>      protected StudyQueryService studyQueryService;
혹시 @MockBean으로 선언한 객체들을 RestDocsTest로 옮겨주실 수 있을까요~?
전에 [컨벤션으로 정했던 내용](https://github.com/BDD-CLUB/01-doo-re-back/discussions/48)이라서요!

2024-02-01 06:01 UTC, amaran-th commented on src/test/java/doore/restdocs/docs/StudyApiDocsTest.java
> +    protected ParticipantRepository participantRepository;
Service를 모킹하게 되면 Repository 객체에 접근할 일이 없으니 이 객체들은 정의하지 않아주셔도 될 것같아요!

2024-02-01 06:01 UTC, amaran-th commented on src/test/java/doore/restdocs/docs/StudyApiDocsTest.java
> +    }
지금 작성하신 테스트 메서드 모두 모킹한 Service가 아니라 실제 Service를 사용하고 있는 것같아요!
Mock Service가 내가 만든 요청(request) 객체가 들어오면 내가 만든 응답(response) 객체를 반환하도록 설정해줘야 합니다!
레퍼런스가 될지 모르겠지만 예시 코드 남깁니다!

```java
@Test
  @DisplayName("특정 게시글을 신고할 수 있다.")
  void addReport() throws Exception {
    // given
    final String accessToken = "Bearer access_token";
    final RequestFieldsSnippet requestFields = requestFields(
        fieldWithPath("reporterId").type(JsonFieldType.NUMBER).description("신고자의 Id"),
        fieldWithPath("reportedId").type(JsonFieldType.NUMBER).description("신고 대상자의 Id(당하는 사람)"),
        fieldWithPath("type").type(JsonFieldType.STRING).description(
            "신고 게시글의 유형(COMMENT, PARTICIPANT, REQUEST_NOTIFICATION)"),
        fieldWithPath("contentId").type(JsonFieldType.NUMBER).description("신고 게시물의 Id")
    );

    final ResponseFieldsSnippet responseFields = responseFields(
        fieldWithPath("id").type(JsonFieldType.NUMBER).description("신고 id"),
        fieldWithPath("reporterId").type(JsonFieldType.NUMBER).description("신고자의 Id"),
        fieldWithPath("reportedId").type(JsonFieldType.NUMBER).description("신고 대상자의 Id)"),
        fieldWithPath("type").type(JsonFieldType.STRING)
            .description("신고 게시글의 유형(COMMENT, PARTICIPANT, REQUEST_NOTIFICATION)"),
        fieldWithPath("contentId").type(JsonFieldType.NUMBER).description("신고 게시물의 Id"),
        fieldWithPath("createdAt").type(JsonFieldType.STRING)
            .description("신고 일자(yyyy:MM:dd:HH:mm:ss)")
    );
    final ReportCreateRequest reportRequest = new ReportCreateRequest(1L, 2L, ReportType.COMMENT,
        1L);

    final ReportCreateResponse reportCreateResponse = new ReportCreateResponse(1L,
        reportRequest.getReporterId(),
        reportRequest.getReportedId(), reportRequest.getType(), reportRequest.getContentId(),
        LocalDateTime.parse("2023-08-09T13:25:00"));

    when(reportCommandService.create(any(), any())).thenReturn(reportCreateResponse);

    // when & then
    mockMvc.perform(post("/reports")
            .header("Authorization", accessToken)
            .contentType(MediaType.APPLICATION_JSON_VALUE)
            .content(objectMapper.writeValueAsString(reportRequest)))
        .andExpect(status().isCreated())
        .andDo(document("add-report", requestFields, responseFields));
  }
```

2024-02-03 06:08 UTC, lcqff commented on src/main/java/doore/study/api/StudyController.java
> +    public ResponseEntity<Void> withdrawParticipant(@PathVariable Long studyId, HttpSession session) {
사용자가 직접 탈퇴하는 기능이라 현재 로그인중인 사용자 정보를 가저오려고 사용했습니다~

2024-02-03 06:09 UTC, lcqff commented on src/test/java/doore/member/domain/repository/ParticipantRepositoryTest.java
> +        );
헉 짱입니다!!

2024-02-03 07:23 UTC, lcqff commented on src/test/java/doore/member/domain/repository/ParticipantRepositoryTest.java
> +        em.clear();
아 헐 대박 save를 사용할때만 즉시 커밋이 되는 줄 알았는데 `SimpleJpaRepository`의 delete 관련 메서드 모두 하나의 트랜잭션을 가지고 있네요!!!!! 

```
	@Override
	@Transactional
	public void deleteAllById(Iterable<? extends ID> ids) {

		Assert.notNull(ids, "Ids must not be null");

		for (ID id : ids) {
			deleteById(id);
		}
	}
```
delete 관련 메서드는 따로 커밋을 해줘야한다고 생각했습니다 그러면 따로 플러쉬 시켜줄 필요가 없네요!! flush clear 코드 삭제하겠습니다~

2024-02-03 07:31 UTC, 02ggang9 reviewed
수고하셨습니다~~ 👍👍 이네용

세션부분이랑 Mocking 부분 해결하시고 다시 Request 걸어주시면 감사하겠습니다!!

2024-02-03 07:31 UTC, 02ggang9 commented on src/main/java/doore/study/api/StudyController.java
> +    public ResponseEntity<Void> withdrawParticipant(@PathVariable Long studyId, HttpSession session) {
로그인하면 토큰이 세션에 저장되지 않고 쿠키에 저장되는 것으로 알고 있습니다! 쿠키에 담겨있는 정보를 토대로 Memebr를 찾고, 삭제하는 방법은 어떨까요?

또, @amaran-th 코드를 다시 봤을 때 로그인 과정에서 Header에 토큰 값들 담기는 하지만 저장하는 과정은 없는 것 같은데 프론트 분께서 직접 쿠키 값에 꼽기로 결정이 된건가용?

2024-02-03 07:31 UTC, 02ggang9 commented on src/main/java/doore/study/api/StudyController.java
> +    public ResponseEntity<List<Participant>> getParticipant(@PathVariable Long studyId) {
이번에는 인텔리제이로 했을 때 테스트가 통과되나용?? @ReuqestMapping이 없어가지고 여쭤봅니다~

2024-02-03 07:31 UTC, 02ggang9 commented on src/test/java/doore/member/domain/repository/ParticipantRepositoryTest.java
> +                .build();
저번에 @amaran-th 님 리뷰에서도 달았는데 KEEPER에서 사용하는 Test Fixture를 한번 도입해 보는건 어떨까요? 도입한다면 줄도 짧아지고 email 같은 경우도 실제 이메일처럼 랜덤한 값을 만들어 줍니다!

2024-02-03 07:31 UTC, 02ggang9 commented on src/test/java/doore/study/application/StudyCommandServiceTest.java
> +                        .hasMessage(INVALID_ENDDATE.errorMessage());
👍👍 입니다~~

2024-02-03 08:02 UTC, lcqff commented on src/test/java/doore/restdocs/docs/StudyApiDocsTest.java
> +    }
헐대박!! reponsebody가 안생긴것도 이거 때문이었군요!!! 짱입니다~!

2024-02-03 08:06 UTC, lcqff commented on src/main/java/doore/study/api/StudyController.java
> +    public ResponseEntity<List<Participant>> getParticipant(@PathVariable Long studyId) {
앗 이거 그 얘기 나오기 전에 올린 PR이여서 수정해야합니다!! ㅎㅎ
그리고 확인하셨을수도 있겠지만 requestMapping 붙여줘도 따로 인텔리제이 설정해야한다고 하네요! 슬랙 확인...

2024-02-03 08:06 UTC, lcqff commented on src/test/java/doore/member/domain/repository/ParticipantRepositoryTest.java
> +                .build();
한번 시도해보겠습니다~

2024-02-03 09:24 UTC, lcqff commented on src/main/java/doore/study/api/StudyController.java
> +    public ResponseEntity<Void> withdrawParticipant(@PathVariable Long studyId, HttpSession session) {
혹시 쿠키 이름은 Bearer Token으로 저장되있는 걸까요??

2024-02-03 09:51 UTC, 02ggang9 commented on src/main/java/doore/study/api/StudyController.java
> +    public ResponseEntity<List<Participant>> getParticipant(@PathVariable Long studyId) {
아하!! 그 전에 올린 PR 이였군요!! 확인했습니다~!

2024-02-03 12:45 UTC, lcqff commented on src/main/java/doore/study/application/StudyCommandService.java
> +    }
이렇게 하는게 맞겠죵?? 틀리면 알려주세요!

2024-02-03 12:45 UTC, lcqff commented on src/main/java/doore/member/exception/MemberExceptionType.java
> +    EMPTY_AUTHORIZATION(HttpStatus.BAD_REQUEST,"권한이 비어있습니다.");
권한 비어있습니다 말고 권한이 없습니다가 나을지....

2024-02-05 07:43 UTC, lcqff commented on src/test/java/doore/restdocs/docs/StudyApiDocsTest.java
> +                .googleId("pom@gmail.com")
@amaran-th  이메일이랑 구글 Id 이렇게 들어가는 거 맞나요?

2024-02-05 11:19 UTC, shkisme approved these changes
수고하셨씁니다

2024-02-05 11:19 UTC, shkisme commented on src/docs/asciidoc/study.adoc
> +== `DELETE`: 참여자 삭제
path parameter를 문서에 추가하면 좋을 것 같습니다!

2024-02-05 11:19 UTC, shkisme commented on src/main/java/doore/member/domain/Participant.java
> +        this.isDeleted = isDeleted;
isDeleted는 편의를 위해서 디폴트로 false로 설정해두는 건 어떨까요?

2024-02-05 11:19 UTC, shkisme commented on src/main/java/doore/study/api/StudyController.java
> +@RequestMapping("")
```suggestion
@RequestMapping
```
생략 가능합니다!

2024-02-05 11:19 UTC, shkisme commented on src/main/java/doore/member/exception/MemberExceptionType.java
> +    EMPTY_AUTHORIZATION(HttpStatus.BAD_REQUEST,"권한이 비어있습니다.");
"권한이 없습니다"는 어떨까요?
그리고 권한 관련한 에러는 401 응답코드를 반환하는 편이 좋을 것 같습니다!

2024-02-05 11:19 UTC, shkisme commented on src/main/java/doore/study/api/StudyController.java
> +    public ResponseEntity<Void> withdrawParticipant(@PathVariable Long studyId, HttpServletRequest request) {
이부분은 추후 권한 관련된 로직이 추가되고 나서 수정되어야 할 것 같습니다!
todo 주석으로 표시해주시면 감사할 것 같습니다!

2024-02-05 11:19 UTC, shkisme commented on src/test/java/doore/member/domain/repository/ParticipantRepositoryTest.java
> +    void findAllByStudyId_특정_스터디의_모든_참여자를_조회할_수_있다_성공() {
저희 RepositoryTest는 직접 작성한 쿼리만 테스트하기로 했었던 것 같습니다~!

2024-02-05 11:20 UTC, amaran-th commented on src/main/java/doore/study/api/StudyController.java
> +    public ResponseEntity<Void> withdrawParticipant(@PathVariable Long studyId, HttpSession session) {
넵 맞습니다!

2024-02-05 11:28 UTC, amaran-th approved these changes

2024-02-05 11:28 UTC, amaran-th commented on src/test/java/doore/restdocs/docs/StudyApiDocsTest.java
> +                .googleId("pom@gmail.com")
구글 ID는 구글에서 부여한 사용자 식별 코드입니다! 대강 10~15자리의 숫자열로 이루어져있어요!

2024-02-05 13:05 UTC, JJimini approved these changes
리뷰가 좀 늦었네요..! 그런데 다른 분들이 이미 다 리뷰해주셔서 할 부분이 많이 없네요..ㅎㅎ 수고하셨습니다~!

2024-02-05 13:05 UTC, JJimini commented on src/main/java/doore/study/api/StudyController.java
> +@RequestMapping("")
슬랙에 제가 올려둔 방법대로 수정하고 테스트하면 `RequestMapping`이 없어도 테스트가 깨지지 않습니다!

2024-02-05 13:05 UTC, JJimini commented on src/main/java/doore/study/api/StudyController.java
> +    public ResponseEntity<List<Participant>> getParticipant(@PathVariable Long studyId) {
엇 위에 `RequestMapping` 관련 제 코멘트 확인 부탁드립니다~!

2024-02-05 13:05 UTC, JJimini commented on src/test/java/doore/study/application/StudyQueryServiceTest.java
> +            );
여기 assert 하는 부분을 assertAll로 한번더 감싸주셨는데 혹시 이유가 있나요??

2024-02-06 13:11 UTC, lcqff commented on src/main/java/doore/study/api/StudyController.java
> +@RequestMapping("")
헉 그래도 RequestMapping은 있어야하는 줄 알았네요 확인입니다!!

2024-02-06 13:27 UTC, lcqff commented on src/test/java/doore/study/application/StudyQueryServiceTest.java
> +            );
조회 했을때 참여자 리스트의 크기가 1이고, 해당 참여자의 id가 memberId와 동일한 경우가 모두 참일 때 테스트를 통과하게 하기 위해 사용했습니다~!
assertAll을 사용하지 않으면 제일 위에 있는 assert문이 실패했을 때 테스트가 종료되지만 assertAll을 사용하면 assertAll 안에 있는 모든 assert문이 선행된 assert문의 실패여부와 관계없이 실행된다고 알고 있습니다!
물론 이런 기능적인 의미도 있지만 개발자에게 해당 테스트가 개별적이지 않다는?점을 직관적으로 전달할 수 있다는 것에도 의미가 있다 생각합니다🧐

2024-02-06 15:17 UTC, merged