refactor: 스터디 조회 기능 수정
BDD-CLUB/01-doo-re-back pull request #90
Opened 2024-02-22 11:09 UTC by lcqff

## #️⃣ 연관된 이슈

close: #89

## 📝 작업 내용

스터디 참여자 개별의 스터디 정보(커리큘럼 정보)를 들고오도록 수정했습니다.
학습자료랑 같이 pr 올리려다가 변경된 파일이 좀 있어서 따로 올립니다!

개별 스터디 정보
```
{
  "studyResponse" : {
    "id" : 1,
    "name" : "알고리즘",
    "description" : "알고리즘 스터디입니다.",
    "startDate" : "2020-01-01",
    "endTime" : "2020-02-01",
    "status" : "IN_PROGRESS",
    "isDeleted" : false,
    "teamId" : 1,
    "cropId" : 1
  },
  "participantId" : 1,
  "PersonalCurriculumItemResponse" : [ {
    "id" : 1,
    "name" : "chapter1. greedy",
    "itemOrder" : 1,
    "isDeleted" : false,
    "isChecked" : false
  } ]
}

```

전체 스터디 정보
```
{
  "studyResponse" : {
    "id" : 1,
    "name" : "알고리즘",
    "description" : "알고리즘 스터디입니다.",
    "startDate" : "2020-01-01",
    "endTime" : "2020-02-01",
    "status" : "IN_PROGRESS",
    "isDeleted" : false,
    "teamId" : 1,
    "cropId" : 1
  },
  "curriculumItems" : [ {
    "id" : 1,
    "name" : "chapter1. greedy",
    "itemOrder" : 0,
    "isDeleted" : false,
    "participantCurriculumItems" : [ {
      "participantId" : 1,
      "isChecked" : false
    } ]
  } ]
}
```

기존에는 스터디 조회시 커리큘럼에서 참여자의 커리큘럼의 체크 여부를 알 수 없었습니다.

## 💬 리뷰 요구사항(선택)

getPersonalStudyDetail이란 메서드명 괜찮은지... ㅠㅠ 
그리고 dto 분리가 잘 된건지도 봐주시면 감사하겠습니다!

2024-02-27 06:51 UTC, shkisme reviewed
기능을 척척척 개발해내시는 모습 멋있습니다
하나 궁금한게 있어서 코멘트 달았어요!

2024-02-27 06:51 UTC, shkisme commented on src/main/java/doore/study/application/dto/response/StudyResponse.java
> +@Embeddable
오....! Dto에 @Embeddable를 적용하신 이유가 궁금하네용~~

2024-02-27 06:51 UTC, shkisme commented on src/main/java/doore/study/application/dto/response/StudyResponse.java
> +    }
Nit: @All/NoArgsConstructor 를 적용해볼 수 있겠네요

2024-02-28 18:49 UTC, lcqff commented on src/main/java/doore/study/application/dto/response/StudyResponse.java
> +@Embeddable
PersonalStudyDetailResponse와 StudyDetailResponse에 모두 스터디와 관련된 동일 필드가 사용되는데 이걸 따로 따로 작성하면 이후 Study 필드가 추가되거나 수정됐을 때 PersonalStudyDetailResponse와 StudyDetailResponse를 각각 수정하기 귀찮을 거 같아서 그냥 @Embeddable로 묶어?버렸습니다 ㅎㅎ... 빼는게 나을까용??

2024-02-29 18:28 UTC, shkisme commented on src/main/java/doore/study/application/dto/response/StudyResponse.java
> +@Embeddable
아하 그런 의도가 있었군요~
혹시 해당 어노테이션이 없다면 정상적으로 동작하지 않나요?

2024-03-01 08:50 UTC, amaran-th requested changes
수고하셨습니다~~!

2024-03-01 08:50 UTC, amaran-th commented on src/main/java/doore/study/application/dto/response/StudyResponse.java
> +    Long teamId;
여기서는 `TeamReferenceResponse`라는 dto를 따로 만들어서 team을 직접참조하는 것은 어떤가요? 보통 스터디를 조회할 때 팀의 id 외의 정보도 필요로 할 것 같아서요

2024-03-01 08:50 UTC, amaran-th commented on src/main/java/doore/study/application/dto/response/StudyResponse.java
> +    Long cropId;
crop도 직접참조시키면 좋을 것 같아요!

2024-03-07 04:42 UTC, lcqff commented on src/main/java/doore/study/application/dto/response/StudyResponse.java
> +    Long teamId;
아하 그러고보니 그러는게 좋겠네요~~~!!! 좋은 지적입니다 감사합니다

2024-03-07 06:27 UTC, shkisme approved these changes
@Embeddable은 없어도 동일한 동작을 할 것 같은데, 확인해보시고 필요없다면 제거하면 될거같습니다~

2024-03-07 10:31 UTC, 02ggang9 commented on src/main/java/doore/study/application/dto/response/StudyResponse.java
> +public class StudyResponse {
요거는 따로 record로 안 하신 이유가 궁금합니다!

2024-03-07 10:31 UTC, 02ggang9 commented on src/main/java/doore/study/application/StudyQueryService.java
> +        return new StudyResponse(study.getId(), study.getName(), study.getDescription(), study.getStartDate(),
생성자 파라미터가 너무 많은데 이럴 경우에는 빌더로 하는건 어떨까용?.?

2024-03-07 10:31 UTC, 02ggang9 approved these changes
굳굳입니다요!

2024-03-07 12:33 UTC, lcqff commented on src/main/java/doore/study/application/StudyQueryService.java
> +        return new StudyResponse(study.getId(), study.getName(), study.getDescription(), study.getStartDate(),
보름님이 DTO에는 빌더 쓰지 말자고 하셔서...🥺

2024-03-07 12:34 UTC, lcqff commented on src/main/java/doore/study/application/dto/response/StudyResponse.java
> +public class StudyResponse {
그 부분은 다른 DTO에 embedded 시켜 줄 애라서 record설정이 안됐습니다!

2024-03-07 12:35 UTC, lcqff commented on src/main/java/doore/study/application/dto/response/StudyResponse.java
> +@Embeddable
@embeddable이나 @embedded 둘 중 하나만 있으면 정상동작하는데 그냥 둘다 명시해두는게 이해가 편할 거 같아서 냅뒀었습니다! (근데 지금은 지움)

2024-03-07 13:29 UTC, shkisme commented on src/main/java/doore/study/application/StudyQueryService.java
> +        return new StudyResponse(study.getId(), study.getName(), study.getDescription(), study.getStartDate(),
헉 아뇨 쓰셔도 됩니다!
제가 쓰지 말라고 했었나요?! 그냥 필드가 하나인 dto에 빌더 쓰신 이유가 궁금해서 질문 드린거였을겁니다!!

2024-03-08 07:24 UTC, lcqff commented on src/main/java/doore/study/application/StudyQueryService.java
> +        return new StudyResponse(study.getId(), study.getName(), study.getDescription(), study.getStartDate(),
제가 잘못기억하고 있었군요~!!!!!
이제부터 빌더쓰겠습니다!!!

2024-03-10 13:56 UTC, amaran-th approved these changes
확인했습니다! 수고하셨습니다~

2024-03-11 00:34 UTC, JJimini approved these changes
수고하셨습니다! 늦어서 죄송합니다ㅠㅠㅠ

2024-03-11 00:34 UTC, JJimini commented on src/main/java/doore/study/application/ParticipantCommandService.java
> +        }
스터디에서는 이 부분을 controller에서 처리했던 것 같은데 참여자에서는 service에서 처리하네요! 통일 하는 것이 좋을 것 같아요~!

2024-03-11 00:34 UTC, JJimini commented on src/main/java/doore/study/application/ParticipantQueryService.java
> +    public List<Participant> findAllParticipants(Long studyId) {
전체를 표현하실 때 스터디에서는 entire를 사용하셨고, 참여자에서는 all을 사용하시는 것 같아요! 이 부분도 통일하는 것이 더 좋아 보입니다! (개인적으로 저는 all에 한표..)

2024-03-11 00:34 UTC, JJimini commented on src/main/java/doore/study/application/StudyQueryService.java
> +        Study study = getStudy(studyId);
스터디를 가져올 때, 팜님처럼 getStudy로 따로 빼두고 호출하여 사용하는 것이 좋은 지, 코드에서 바로 `studyRepository.findById(studyId).orElseThrow(() -> new StudyException(NOT_FOUND_STUDY));` 를 써주는 게 좋을 지 궁금합니다! 코드 길이에는 별로 차이가 없는 것 같은데, 계속 호출하는 과정이 있어서 성능 측면에서 어떤 방식이 더 효율적일지 궁금하네요..

2024-03-13 04:22 UTC, lcqff commented on src/main/java/doore/study/application/StudyQueryService.java
> +        Study study = getStudy(studyId);
저같은 경우에는 여러 메소드에서 동일한 Exception을 사용하는 경우 Exception을 빼주고 하나에만 사용되는 경우에는 그냥 그대로 사용했습니다~ 사실 성능적인 부분보다는 계속 동일한 코드(`studyRepository.findById(studyId).orElseThrow(() -> new StudyException(NOT_FOUND_STUDY));`)를 작성하려니 귀찮아서^^;;; 메소드 분리하는 정도로 큰 성능차이는 없을거라 생각합니다! 개발자 취향차 아닐까 생각하고 있습니다🤔

2024-03-13 04:22 UTC, lcqff commented on src/main/java/doore/study/application/ParticipantQueryService.java
> +    public List<Participant> findAllParticipants(Long studyId) {
저도 all에 한표 하겠습니다~!

2024-03-13 04:42 UTC, merged